### ISSUE TITLE
Cross-Side-Scripting protection Problems

### ISSUE THREAD

**Issue by Akasch** [JohnMcLear/ep_pad_activity_nofication_in_title#1]
If a Pad with this Plugin is embedet in a Iframe of an other side there is a cross-side-scripting error:

    Uncaught SecurityError: Blocked a frame with origin "https://ep.mafiasi.test" from accessing a frame with origin "https://mafiasi.test". The frame requesting access set "document.domain" to "ep.mafiasi.test", but the frame being accessed did not. Both must set "document.domain" to the same value to allow access.

(error from Chromium, Firefox seems not to show it but just end the script)

I have tryed to set document.domain="mafiasi.de" but the error is more or less the same then.

**Comment by JohnMcLear** [comment]
Give the new version a try.  If you get no dice you have XHR issues.
